// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3MWZNZdHvMfzU9hTbc_Tu6-8qD8z-kL0',
    appId: '1:559942189581:web:555c2beaffd5cfbd174b44',
    messagingSenderId: '559942189581',
    projectId: 'kigali-services-4f3c9',
    authDomain: 'kigali-services-4f3c9.firebaseapp.com',
    storageBucket: 'kigali-services-4f3c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFpJ8Mrxdz2p4ud6KzOJIgyt4jUGtsTc',
    appId: '1:559942189581:android:40625b6d33b84029174b44',
    messagingSenderId: '559942189581',
    projectId: 'kigali-services-4f3c9',
    storageBucket: 'kigali-services-4f3c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiK2V86f8etmCfpYD_UJdhN5CMkZKUvkg',
    appId: '1:559942189581:ios:36df3ff430c16762174b44',
    messagingSenderId: '559942189581',
    projectId: 'kigali-services-4f3c9',
    storageBucket: 'kigali-services-4f3c9.firebasestorage.app',
    iosBundleId: 'com.joshuamoses.kigaliServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiK2V86f8etmCfpYD_UJdhN5CMkZKUvkg',
    appId: '1:559942189581:ios:36df3ff430c16762174b44',
    messagingSenderId: '559942189581',
    projectId: 'kigali-services-4f3c9',
    storageBucket: 'kigali-services-4f3c9.firebasestorage.app',
    iosBundleId: 'com.joshuamoses.kigaliServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3MWZNZdHvMfzU9hTbc_Tu6-8qD8z-kL0',
    appId: '1:559942189581:web:fa309b52361f2454174b44',
    messagingSenderId: '559942189581',
    projectId: 'kigali-services-4f3c9',
    authDomain: 'kigali-services-4f3c9.firebaseapp.com',
    storageBucket: 'kigali-services-4f3c9.firebasestorage.app',
  );
}
